### ISSUE TITLE
bug: build 打包发版时报错 Cannot find module 'umi/dist/cli/node'

### ISSUE THREAD

**Issue by Promisezhangbo** [umijs/dumi#1938] opened 2023-10-11 11:28 UTC
### Version

2.2.0

### OS Version

macos 13.3.1

### Node.js Version

yarn run v1.22.19

### Browser Version

google: 117.0.5938.149

### Link to minimal reproduction

无

### Steps to reproduce

发版时在流水线中build的步骤报错
<img width="1158" alt="image" src="https://github.com/umijs/dumi/assets/104294824/72faebb2-8136-45c1-a769-d8d3c3802c85">

### What is expected?

预期正常build

### What is actually happening?

流水线在执行到build的时候报错 Error: Cannot find module 'umi/dist/cli/node'

**Comment by Promisezhangbo** [comment] 2023-10-11 11:30
补充一下包的版本
father: 4.3.1
yarn: 1.22.19
dumi: 2.2.0

**Comment by PeachScript** [comment] 2023-10-12 03:14
Duplicate of https://github.com/umijs/dumi/issues/1916#issuecomment-1736597602

**Closed by PeachScript** 2023-10-12 03:14 UTC
Labels: unconfirmed
