### ISSUE TITLE
bug: hash history模式下md中标题生成的a标签链接有误

### ISSUE THREAD

**Issue by leegsen7** [umijs/dumi#1712] opened 2023-06-02 02:00 UTC
### Versions

- dumi: 2.1.13
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce
md标题生成的a标签链接并未带上hash route path，导致点击链接跳转错误
![image](https://github.com/umijs/dumi/assets/15691486/9aff3535-a95e-4f8b-ae1d-df6b6b929807)
`toc: content` 配置生成的a标签是正常的
![image](https://github.com/umijs/dumi/assets/15691486/a1254593-7fab-407b-9e2f-9b24df788c97)

**Comment by PeachScript** [comment] 2023-06-02 06:33
dumi 2 没有正式支持 hash 路由，启动时应该会收到警告，现阶段建议用 browser 路由

**Comment by PeachScript** [comment] 2023-06-02 06:33
Duplicate of #1553

**Closed by PeachScript** 2023-06-02 06:33 UTC
Labels: bug
