### ISSUE TITLE
dumi code标签如何控制不展示包裹器

### ISSUE THREAD

**Issue by parlay96** [umijs/dumi#2181] opened 2024-07-29 07:59 UTC
### What problem does this feature solve?

![image](https://github.com/user-attachments/assets/315160b7-9287-4c31-9dd5-836e8921bc4f)
dumi code标签如何控制不展示包裹器

**Comment by PeachScript** [comment] 2024-07-29 08:50
Duplicate of #2180

**Closed by PeachScript** 2024-07-29 08:50 UTC
Labels: enhancement
