### ISSUE TITLE
bug: 不相同的code标签，渲染却都是同一个demo

### ISSUE THREAD

**Issue by linmingdao** [umijs/dumi#1748] opened 2023-06-19 11:37 UTC
<img width="598" alt="image" src="https://github.com/umijs/dumi/assets/20104800/a95c043b-02a2-4112-9af4-995ea6280974">

### Versions

- dumi:^2.2.0
- node:16.16.0
- npm:8.11.0
- OS:mac OS
- Browser:谷歌

**Comment by PeachScript** [comment] 2023-06-20 01:40
Duplicate of https://github.com/umijs/dumi/issues/1440#issuecomment-1461660100

**Comment by PeachScript** [comment] 2023-06-20 01:40
解法：确保 demo 文件名唯一或手动指定 id

**Closed by PeachScript** 2023-06-20 01:40 UTC
Labels: bug
