### ISSUE TITLE
bug:  打包生成了无效名称文件，win 10环境

### ISSUE THREAD

**Issue by NARUTOne** [umijs/dumi#2138] opened 2024-06-06 08:27 UTC
### Version

2.3.4

### OS Version

window 10

### Node.js Version

16.19.0

### Browser Version

chrome 125

### Link to minimal reproduction

无

### Steps to reproduce

 dumi build 打包后生成了两个在win10下无效名称文件，meta__H:.fa86a119.chunk.css，meta__H:.1ab73d77.async.js，导致ChunkLoadError     at __webpack_require__.f.j

### What is expected?

文件名有效

### What is actually happening?

无效文件名

**Comment by PeachScript** [comment] 2024-06-11 09:02
Duplicate of #1990

**Closed by PeachScript** 2024-06-11 09:02 UTC
Labels: unconfirmed
