### ISSUE TITLE
bug: 文档部署到gitlabPages demo代码区域不展示 需手动刷新

### ISSUE THREAD

**Issue by GzxNydia** [umijs/dumi#692] opened 2021-05-17 11:33 UTC
### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

### What is actually happening?
[](url)

**Comment by xrkffgg** [comment] 2021-05-17 12:14
Duplicate of https://github.com/umijs/dumi/issues/682

**Closed by xrkffgg** 2021-05-17 12:14 UTC
Labels: bug
