### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by tomee-oy** [umijs/dumi#458] opened 2020-12-30 03:08 UTC
### Versions

- dumi: ^1.0.38
- node: 14.7.0
- npm: 6.14.7
- OS: macOS Mojave 10.14.6
- Browser: google 87.0.4280.88

### Steps to reproduce

I have set repository in package.json like this:
```json
 "repository": {
    "type": "git",
    "url": "http://10.12.3.198/bigdata/frontend/cmiot-basic.git"
 },
```

### What is Expected?

"Edit this doc on GitHub" will show out at the footer

### What is actually happening?

The "Edit this doc on GitHub" not show

**Comment by xrkffgg** [comment] 2020-12-30 03:11
Duplicate of https://github.com/umijs/dumi/issues/457

**Closed by xrkffgg** 2020-12-30 03:11 UTC
Labels: bug
