### ISSUE TITLE
bug: dumi 在npm run start 时报错

### ISSUE THREAD

**Issue by Promisezhangbo** [umijs/dumi#1927] opened 2023-10-07 09:36 UTC
### Version

2.2.5

### OS Version

macos 13.3.1

### Node.js Version

16.17.0

### Browser Version

google: 117.0.5938.149

### Link to minimal reproduction

无

### Steps to reproduce

进入到当前项目的根目录，运行npm run start 报错，但是运行 npm run build 可以正常运行
![image](https://github.com/umijs/dumi/assets/104294824/e2b327fa-9ed4-47ea-9f82-1d363854c6ee)

<img width="1000" alt="image" src="https://github.com/umijs/dumi/assets/104294824/735bb02c-8f12-4205-8764-ed3c0111a458">

### What is expected?

预期能正常启动

### What is actually happening?

。

**Comment by PeachScript** [comment] 2023-10-07 12:00
Duplicate of https://github.com/umijs/dumi/issues/1916#issuecomment-1736597602

**Closed by PeachScript** 2023-10-07 12:00 UTC
