### ISSUE TITLE
hash 路由和文档中的标题 hash 冲突

### ISSUE THREAD

**Issue by DaphnisLi** [umijs/dumi#1965] opened 2023-11-21 09:31 UTC
### Version

2.2.14

### OS Version

macOS14.1.1

### Node.js Version

16.20.1

### Browser Version

Google Chrome 版本 119.0.6045.159（正式版本） (x86_64)

### Link to minimal reproduction

无

### Steps to reproduce

页面初始化后点击 “简单示例左侧的 #”，结果会导致原有的 hash 缺失
![image](https://github.com/umijs/dumi/assets/67792799/efaae522-f2c5-4c3a-9d1b-ecab962a5d56)
![image](https://github.com/umijs/dumi/assets/67792799/d4a29b74-04f1-49af-b0fa-58d8f3e24e2b)

### What is expected?

预期应该再 /#/hh-component/filte#简单示例

### What is actually happening?

...

**Comment by PeachScript** [comment] 2023-11-21 09:45
Duplicate of #1553

**Closed by PeachScript** 2023-11-21 09:45 UTC
Labels: unconfirmed
