### ISSUE TITLE
bug: 脚手架拉下来运行报错 SyntaxError:  'import' and 'export' may only appear at the top level. 

### ISSUE THREAD

**Issue by lcy8413685** [umijs/dumi#1973] opened 2023-11-29 06:20 UTC
### Version

v2.2.14

### OS Version

window10

### Node.js Version

v14.17.6

### Browser Version

Chrome 119.0.6045.160

### Link to minimal reproduction

脚手架

### Steps to reproduce

按照官方文档示例下载脚手架，运行报错，以为是node版本问题，但是切换了多个版本node还是报错，希望能帮忙解决一下
Module build failed (from ./node_modules/@umijs/bundler-webpack/compiled/babel-loader/index.js):
SyntaxError: D:\work\workspace\demo2\docs\test.md?type=meta: 'import' and 'export' may only appear at the top level. (6:0)

### What is expected?

脚手架能正常运行

### What is actually happening?

脚手架运行报错

**Comment by PeachScript** [comment] 2023-11-29 10:59
Duplicate of #1701

**Closed by PeachScript** 2023-11-29 10:59 UTC
Labels: unconfirmed
