### ISSUE TITLE
路由错乱

### ISSUE THREAD

**Issue by lindaJNlinda** [umijs/dumi#1043] opened 2022-03-07 14:43 UTC
###
自定义menus
两个文档：
packages/admin/docs/button
packages/h5/docs/button

配置  includes: ['packages/admin/docs', 'packages/h5/docs'],
      menus:{'/admin':{ title: "基础组件",children:[ "button/index.md",]}, '/h5':{ title: "基础组件",children:[ "button/index.md",]}}
     navs:[ {title: 'Admin',path: '/admin' },{title: 'H5', path: '/h5' },]

导致无法找到 h5 下面的button ,侧边栏永远展示的是admin下面的button .这种情况应该如何处理呢？

**Comment by PeachScript** [comment] 2022-03-08 02:01
Duplicate of #624

**Closed by PeachScript** 2022-03-08 02:01 UTC
Labels: question
