### ISSUE TITLE
bug: 中英文切换时，代码块不变化

### ISSUE THREAD

**Issue by wabi-habi** [umijs/dumi#1791] opened 2023-07-28 01:46 UTC
### Versions

- dumi: ^2.2.1
- node: v18.16.0
- npm: 9.8.1
- OS: MacOS 12.6 M1
- Browser: Google Chrome 115.0.5790.102（正式版本） (arm64)

### Steps to reproduce

[https://github.com/wabi-habi/dumi-test](https://github.com/wabi-habi/dumi-test)

<img width="1738" alt="image" src="https://github.com/umijs/dumi/assets/99811051/7ecb4bde-a14c-4f7c-9e06-ace568041a6b">

<img width="1738" alt="image" src="https://github.com/umijs/dumi/assets/99811051/7ecb4bde-a14c-4f7c-9e06-ace568041a6b">

<img width="1737" alt="image" src="https://github.com/umijs/dumi/assets/99811051/6b0092af-37aa-473a-9ee0-4d13ba9a02b6">

### What is Expected?

切换到英文时代码块也应该发生变化

### What is actually happening?

切换到英文时代码块不变！还是中文的

**Comment by PeachScript** [comment] 2023-07-28 04:40
Duplicate of #1780

**Closed by PeachScript** 2023-07-28 04:40 UTC
Labels: bug
