### ISSUE TITLE
bug: 和umi使用出现错误 cannot resolve module @/components/***

### ISSUE THREAD

**Issue by zhouzyc** [umijs/dumi#983] opened 2021-12-16 02:38 UTC
### Versions

- dumi: v1.1.36
- node:v14.17.5
- npm:v6.14.14
- OS:
- Browser:

### What is actually happening?
错误发生在，我升级umi扩展
-"@umijs/preset-react": "^1.8.24"
+"@umijs/preset-react": "^2.1.0"

![1639620501315](https://user-images.githubusercontent.com/18420689/146294889-27696068-d5d5-4161-91b4-96b02725a5be.jpg)

**Comment by zhouzyc** [comment] 2021-12-16 02:57
复现demo：
https://gitee.com/umijs-admin-react/react-umijs-admin.git
安装步骤升级：
-"@umijs/preset-react": "^1.8.24"
+"@umijs/preset-react": "^2.1.0"
复现问题

**Comment by webmatrixxxl** [comment] 2022-05-16 14:26
@zhouzyc, have you found a fix for this?

**Comment by webmatrixxxl** [comment] 2022-05-16 15:15
@zhouzyc the problem is with case-sensitive paths in OS.

**Closed** 2022-06-21 09:17 UTC
Labels: bug, need reproduce
