### ISSUE TITLE
bug: yarn create @umijs/dumi-lib --site 生成的项目 run build 报错

### ISSUE THREAD

**Issue by WuHuSa** [umijs/dumi#925] opened 2021-10-30 05:55 UTC
### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce
yarn create @umijs/dumi-lib --site 生成的项目
yarn build
报错 Cannot read property 'path' of undefined 

### What is Expected?
能正常 build

### What is actually happening?
报错打断

**Comment by PeachScript** [comment] 2021-10-30 12:39
Duplicate of https://github.com/umijs/father/issues/418

**Closed** 2021-10-30 12:39 UTC
Labels: bug
