### ISSUE TITLE
bug: defineApp 未导出

### ISSUE THREAD

**Issue by DaphnisLi** [umijs/dumi#2003] opened 2024-01-10 03:22 UTC
### Version

2.2.6

### OS Version

macOS 14.2.1 (23C71)

### Node.js Version

v16.20.1

### Browser Version

Google Chrome 版本 119.0.6045.159（正式版本） (x86_64)

### Link to minimal reproduction

无

### Steps to reproduce

1

### What is expected?

1

### What is actually happening?

1

### Any additional comments? (optional)

1

**Comment by PeachScript** [comment] 2024-01-23 05:34
Duplicate of #2004

**Closed by PeachScript** 2024-01-23 05:34 UTC
Labels: unconfirmed
