### ISSUE TITLE
bug: dumirc中配置mfsu.exclude后编译出错

### ISSUE THREAD

**Issue by suyue0731** [umijs/dumi#1538] opened 2023-03-10 08:13 UTC
### Versions

- dumi: 2.1.15
- node: 14.18.2
- yarn: 1.9.4
- OS: Mac11.3.1
- Browser: Chrome

### Steps to reproduce
[test-dumi.zip](https://github.com/umijs/dumi/files/10939934/test-dumi.zip)
这里提供一个最小可复现代码，yarn install之后npm start即可复现编译失败
### What is Expected?
期望可以正常编译
### What is actually happening?
<img width="675" alt="image" src="https://user-images.githubusercontent.com/18397351/223397722-fe145581-2de9-482d-9141-5a9adfb8e5eb.png">

**Comment by PeachScript** [comment] 2023-03-10 08:14
Duplicate of #1530

**Closed by PeachScript** 2023-03-10 08:14 UTC
Labels: bug
