### ISSUE TITLE
自动生成api表格报错，提示说找不到属性定义，而且一修改代码就报错。

### ISSUE THREAD

**Issue by 97vack** [umijs/dumi#1787] opened 2023-07-26 03:37 UTC
### Question
自动生成api表格报错，老是提示说找不到
### Sample Code
![image](https://github.com/umijs/dumi/assets/33567483/61b5437f-97c8-42ba-9aa7-8efb55021aa5)
![image](https://github.com/umijs/dumi/assets/33567483/80a89844-c006-4789-be9e-0d47ef7e9326)
![image](https://github.com/umijs/dumi/assets/33567483/b9b4c620-b867-4ae5-932a-02d5aa7b87a0)
![image](https://github.com/umijs/dumi/assets/33567483/82bcf1e3-39fe-487b-a85d-809aad62d1ec)
![image](https://github.com/umijs/dumi/assets/33567483/75bf0d75-25ba-4612-b6b0-f612d41a072e)
然后我一修改代码就提示报错
![image](https://github.com/umijs/dumi/assets/33567483/4d9ca957-1d9c-4366-ae93-53267b36b1e2)

**Comment by 97vack** [comment] 2023-07-26 03:38
![image](https://github.com/umijs/dumi/assets/33567483/f8175dca-26b1-4254-b3bf-6ddabe166768)

**Comment by 97vack** [comment] 2023-07-26 03:39
![image](https://github.com/umijs/dumi/assets/33567483/436ca213-db05-4543-abac-d56a95e5321f)

**Comment by PeachScript** [comment] 2023-07-26 07:36
Duplicate of #1476

**Comment by PeachScript** [comment] 2023-07-26 07:36
暂时不支持 Windows 系统，等 #1653 修复

**Closed by PeachScript** 2023-07-26 07:36 UTC
Labels: question

**Comment by 97vack** [comment] 2023-07-26 07:50
请问大概什么时候可以提供支持

**Comment by Col0ring** [comment] 2023-07-27 02:15
> 暂时不支持 Windows 系统，等 #1653 修复

mac 也有这种情况，而且也是修改代码就报错，看着像是 esbuild 那块出问题了
```txt
node:internal/event_target:912
  process.nextTick(() => { throw err; });
                           ^
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: 加载失败: (449)[xxxx [".d.ts",".ts",".tsx","/index.d.ts","/index.ts","/index.tsx","",".js",".jsx","/index.js","/index.jsx"]]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```
![image](https://github.com/umijs/dumi/assets/47329987/406a89ed-0c55-4377-bfa6-688243aeebeb)

**Comment by AirmaZ** [comment] 2025-08-07 09:12
> > 暂时不支持 Windows 系统，等 [#1653](https://github.com/umijs/dumi/pull/1653) 修复
> 
> mac 也有这种情况，而且也是修改代码就报错，看着像是 esbuild 那块出问题了
> 
> node:internal/event_target:912
>   process.nextTick(() => { throw err; });
>                            ^
> [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: 加载失败: (449)[xxxx [".d.ts",".ts",".tsx","/index.d.ts","/index.ts","/index.tsx","",".js",".jsx","/index.js","/index.jsx"]]".] {
>   code: 'ERR_UNHANDLED_REJECTION'
> }
> ![image](https://github.com/umijs/dumi/assets/47329987/406a89ed-0c55-4377-bfa6-688243aeebeb)

同样的问题，在windows上
