### ISSUE TITLE
bug: 在demo中引入 antd 会报错

### ISSUE THREAD

**Issue by ifreeWorld** [umijs/dumi#1361] opened 2022-12-07 13:15 UTC
### Versions

- dumi:2.0.5
- node:v14.17.6
- npm:
- OS:
- Browser:

### Steps to reproduce
![image](https://user-images.githubusercontent.com/31157002/206185096-b99d967a-4477-437e-88fc-4d582102272e.png)
![image](https://user-images.githubusercontent.com/31157002/206188517-d8dd4989-9006-45c9-9fe4-f35ebd72b359.png)
![image](https://user-images.githubusercontent.com/31157002/206188653-4cdd5262-e861-4954-921d-080db6f22ca3.png)

### What is actually happening?
在demo中引入 antd 会报错，在package.json中已经安装过了，我直接引入一个antd的Button，然后就报错了

**Comment by PeachScript** [comment] 2022-12-07 15:27
Duplicate of #1348

**Comment by PeachScript** [comment] 2022-12-07 15:27
下个版本修复

**Closed by PeachScript** 2022-12-07 15:27 UTC
Labels: bug

**Comment by ifreeWorld** [comment] 2022-12-08 00:06
新版本啥时候发呢
